<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\BidiClasses.trie" />
    <None Remove="Resources\GraphemeClusterClasses.trie" />
    <None Remove="Resources\LineBreakClasses.trie" />
    <None Remove="Resources\WordBoundaryClasses.trie" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\BidiClasses.trie" />
    <EmbeddedResource Include="Resources\GraphemeClusterClasses.trie" />
    <EmbeddedResource Include="Resources\LineBreakClasses.trie" />
    <EmbeddedResource Include="Resources\WordBoundaryClasses.trie" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.5" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" />
  </ItemGroup>
</Project>
