<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fontawesome.ttf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="fontawesome.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Topten.RichTextKit\Topten.RichTextKit.csproj" />
  </ItemGroup>

</Project>
